hhvm/sources/package

http://dl.hhvm.com/source/ has existed for several months now, but is completely empty. Here's a script (based heavily/entirely on the Debian package script) that makes a source tarball from the version given on the command line, and--like the Debian script--rsyncs to dl.hhvm.com.
I couldn't test the rsync-ing part, but it did successfully build a .tar.bz2 file on my machine (e.g. ``./package 3.3.2``).
I also have a variant of this that does nightly tarballs, but those aren't as valuable (people should just checkout master at that point), so this script ignores nightly versions.

Add a script to build a source tarball from a given git tag.

---

hhvm/deb/skeleton/DEBIAN/postinst

According to the [Debian Policy Manual](https://www.debian.org/doc/debian-policy/ch-opersys.html) this is the way to start a service after installation.
This starts HHVM not matter if it was started before the upgrade and it starts HHVM after the first installation. I don't know if this is the best approach but it seemed reasonable to me.
Fixes #103

Start HHVM after installation

---

hhvm/deb/skeleton/DEBIAN/postinst
hhvm/deb/skeleton/etc/hhvm/php.ini

/var/lib/php5 might not exists on every system and doesn't seem to be
a very good place to store HHVM's session data either way.
This change creates a new directory /var/lib/hhvm with the same permissions
as the old /var/lib/php5. It also updates the default php.ini to store the
session data there.
Resolves #101
Resolves #81

Save session to new directory /var/lib/hhvm

---

hhvm/deb/skeleton/DEBIAN/preinst

This will stop upstart hhvm if used, otherwise it will do /etc/init.d/hhvm stop
This mirrors postinst

use invoke-rc.d to stop hhvm

---

hhvm/deb/skeleton/DEBIAN/postinst

Rather than always using www-data:www-data, use the values provided in /etc/default/hhvm if they've been specified.
Fixes facebook/hhvm#6383

Use the default user/group if provided

---

hhvm/deb/package
hhvm/deb/skeleton/etc/hhvm/server.ini

The /var/run directory may be a relatively small tmpfs. The hhvm.hhcm file can
easily grow to fill this filesystem.

Use /var/cache/hhvm for default hhvm.repo.central.path

---

bin/promote-nightly-to-release

Check that $SED is executable

---

aws/bin/update-repos

When updating many releases, we got timeouts due to this.
refs #175
Test Plan: ship this today, check the nightlies tomorrow

When adding a new version to repos, only download that version

---

CURRENT_TARGETS

This always fails in `apt-get update` because artful is unsupported and its repositories no longer exist.
Since it's been that way for the last few versions and no one has complained, I guess we can just remove it from the list?

remove artful from 3.30 targets

---

aws/lambdas/hhvm-get-build-status/index.js

Before:
```
$ curl https://hhvm.com/api/build-status/4.18.1 | jq
{
"success": false,
"version": "4.18.1",
"succeeded": [
"macos-high_sierra",
"macos-mojave",
"debian-8-jessie",
"debian-9-stretch",
"ubuntu-14.04-trusty",
"ubuntu-16.04-xenial",
"ubuntu-18.04-bionic",
"ubuntu-18.10-cosmic",
"ubuntu-19.04-disco"
],
"failed": {
"source": "https://dl.hhvm.com/source/hhvm-4.18-4.18.1.tar.gz",
"source_gpg": "https://dl.hhvm.com/source/hhvm-4.18-4.18.1.tar.gz.sig"
}
}
```
After:
```
$ curl https://hhvm.com/api/build-status/2019.08.15 | jq
{
"success": true,
"version": "2019.08.15",
"succeeded": [
"macos-high_sierra",
"macos-mojave",
"source",
"source_gpg",
"debian-8-jessie",
"debian-9-stretch",
"ubuntu-14.04-trusty",
"ubuntu-16.04-xenial",
"ubuntu-18.04-bionic",
"ubuntu-18.10-cosmic", …
```

Fix build-status for source tarballs

---

DEBUGGING.md

With failed builds last night, I:
- made build logs go to CloudWatch
- made failed builds upload the build environment to Elastic Container
Registry
Document how to use them.

Add DEBUGGING.md

---

aws/userdata/make-binary-package.sh

While I'm here, also stop keeping the workers alive for 3 hours after
a failed build. Logs seem to work well.
closes #199

Stop creating docker images for succesful builds

---

CURRENT_TARGETS

Test Plan:
Manual build in progress; will not land if fails, or if the repo update
fails.
Build log ID is
`2019/09/20/hhvm-2019.09.20_debian-10-buster_i-053434a6d708c0830`

Enable debian-10-buster support

---

aws/hhvm1/lambdas/activities.py
aws/hhvm1/lambdas/check_if_repos_changed.py
aws/hhvm1/lambdas/common.py
aws/hhvm1/lambdas/prepare_activity.py
aws/hhvm1/lambdas/test.py
aws/hhvm1/state-machine/generate.hack
aws/hhvm1/worker/run-test-workers.sh
aws/hhvm1/worker/worker.sh
aws/userdata/trigger-macos-builds.sh

This built yesterday's release and nightly.
Code that runs on Azure is in this homebrew-hhvm branch: https://github.com/hhvm/homebrew-hhvm/tree/build-triggers
I don't know why everything conveniently fails exactly when I need to test error handling but check out how the Azure build [failed and got automatically retried](https://dev.azure.com/hhvm-oss/hhvm-oss-builds/_build?definitionId=1).

trigger MacOS builds from AWS

---

bin/aws-build-status

Example runs:
```
$ bin/aws-build-status
--------------------------------------------------------------------------------------------
|                                      ListExecutions                                      |
+-----------------------------------------------------------------------------+------------+
|                                    name                                     |  status    |
+-----------------------------------------------------------------------------+------------+
|  4.32.0-jjergus-2019-11-18-09-41                                            |  SUCCEEDED |
|  6384d65c-e75c-0bfa-cf09-7722db64791d_498d26f9-db6f-868f-7d94-5b7e4b8095fe  |  SUCCEEDED |
|  ff503c2d-64f2-3330-fce9-5dbf640df4d5_ee03f01b-ef03-030d-8861-721836c2d23b  |  SUCCEEDED |
| …
```

convenient script for build status/output

---

bin/make-source-tarball

- fixed mysql path (or was that not meant to be mysql?)
- also remove boost docs and tests
This gets it down from ~260MB to ~115MB.
I'm runnning a test build now to see if this causes any problems.

fix source tarball cleanup

---

bin/aws-build-status
bin/test-build-on-all-distros

I've done this manually a few times and it was very convenient.
It creates and uploads a source tarball with a fake version number, then runs the AWS build but **only** the MakeBinaryPackage step so nothing gets published. Docker images are also created so failures are easy to investigate on an OnDemand server.

script to test build on all platforms

---

RELEASE_PROCESS.md

I've found it much nicer to use than the CLI, you can expand any commit
message inline or click through to things...

add GitHub UI link to RELEASE_PROCESS.md

---

debian-8-jessie/debian/control
debian-9-stretch/debian/control
ubuntu-18.04-bionic/debian/control

I didn't see any errors on any of the supported systems (probably they all have a good enough version of python installed by default) but I guess it's better to declare it as an explicit dependency just in case?
I can update https://github.com/facebook/hhvm/pull/8665 to prefer python3 if available but if it builds successfully with any version of python maybe that's not necessary.

add python3 to build-depends

---

aws/ondemand/facebook/hhvm/init-container.sh

- `set background=dark` - no one uses white on black terminals, right?
- tabstop=2, softtabstop=2: FB uses 2-space tabs
- expandtabs: ... actually, we use spaces
My preference, but hopefully uncontenious
- make 'backspace' allow deletion of more things
- enable mouse support in all modes

More involved vimrc for hhvm ondemands

---

aws/ondemand/facebook/hhvm/init-container.sh

- using https for facebook as we shouldn't push there, and auth is
unnecessary
- using ssh for staging as auth is required, and pushing sometimes makes
sense

Add 'facebook' and 'staging' remotes to ondemands

---

ubuntu-18.04-bionic/debian/hhvm-nightly-dev.install.in

refs #249
Packages currently have a `lib/lib` subpath in them; as `grep` shows
no `lib/lib` in this repo and other entries in this file do not have the
final component, I'm assuming this is correct. Will test before landing.

Remove duplicate `lib/` from install destinations

---

aws/lambdas/create-s3-index-html/index.js
aws/lambdas/create-s3-index-html/yarn.lock

This lambda has been failing recently because we were hitting the CloudFront limit of 3000 invalidations.
We can avoid that by only regenerating indices for dirs that have any recently modified files, which also makes it much faster.

create-s3-index-html: skip not recently modified

---

aws/hhvm1/lambdas/common.py
aws/hhvm1/lambdas/test.py
aws/lambdas/hhvm-get-build-status/index.js

Needed for https://github.com/facebook/hhvm/pull/8813, because the latest Folly doesn't compile on MacOS 10.14.

drop support for MacOS 10.14 (Mojave)

---

aws/hhvm1/worker/worker.sh

For some reason the AWS EC2 instance sometimes doesn't shut down and just hangs there forever, even though the logs clearly show that it reached the shutdown command and ran it (I just had to manually terminate 6 instances that were created at different points over the last few weeks, it seems completely random).
I don't know what causes it, but maybe this simple hack will help?

retry shutdown in worker.sh

---

ubuntu-18.04-bionic/debian/rules

According to the [build status](https://hhvm.com/api/build-status/2021.11.16), the nightly build continuously fails, while the build succeeded when manually retrying on a devserver.
This might be due to out of memory, and hopefully the issue could be fixed by limiting the concurrency in this PR.

Limit the Make concurrency to 8 threads

---

bin/promote-nightly-to-release

- move stuff around so that `--dry-run` can be used to test this
- Use `--push` URLs so support pulling from https and pushing with ssh.
This lets you pull/rebase etc without access to an SSH key, which is
convenient if it's stored on a yubikey for example
- Provide fix instructions
Test Plan:
```
$ git remote set-url --push origin https://example.com
$ bin/promote-nightly-to-release 2021.11.18 4.136 --dry-run --force
----------------
--- Versions ---
----------------
Nightly build:
2021.11.18
Previous version:
4.135
Tagging version:
4.136
----------------
[WARNING - FORCED] Run from master branch.
[WARNING - FORCED] Uncommitted changes.
[WARNING - FORCED] Git origin push URL is unsupported:
- Current value: https://example.com
- Required value: git@github.com:hhvm/packaging.git
- Fix: …
```

Add fix instructions to incorrect origin message.

---

aws/hhvm1/worker/after-task/make-binary-package.sh

Using the existing bucket for now; will make another one with custom
retention policies if we can't fix the flakiness quickly.
Test Plan:
Shellcheck.
Land. Tomorrow:
- check for corresponding success/failure docker images
- check for log files in s3 if there are failures
- revert if there's problems, so we get good signal over the holidays

Save build failure logs to S3

---

bin/check-build-results

Gives detailed information on the step functsions and intermediate jobs,
including ec2 instance IDs that can be correlated
Example output: https://gist.github.com/fredemmott/3963780a0b87bcd4ba4038c97a927422

Add detailed  'check-build-results' script

---

aws/hhvm1/state-machine/generate.hack

It takes 2h 56m 26s to complete [the build for 2022.02.02](https://dev.azure.com/hhvm-oss/hhvm-oss-builds/_build/results?buildId=1700&view=results), which is close to the 3 hour limit. Also there are previous builds failed due to time out.
This PR increases the timeout to reduce timeout errors.

Increase the build timeout

---

aws/ondemand/facebook/hhvm/init-container.sh

These settings are necessary for the VS Code CMake extension.
Tested by manually creating the file in the build container.

Create VS Code settings.json for development in a build container

---

aws/ondemand/facebook/hhvm/init-container.sh

#279 did not work as expected because `${workspaceFolder}` was considered as a shell environment variable, while it should be a VS Code predefined variable.
This PR instead use single quoted heredoc to prevent `${workspaceFolder}` from being expanded by the shell.

Don't escape `${workspaceFolder}`

---

aws/hhvm1/lambdas/activities.py
aws/hhvm1/lambdas/test.py

According to https://aws.amazon.com/ec2/instance-types/, `r6i.4xlarge` doubles the memory in comparison to `m5.4xlarge`. Hopefully it would reduce the out of memory errors.

Run MakeBinaryPackage on r6i.4xlarge EC2 instances instead of m5.4xlarge

---

aws/ondemand/facebook/hhvm/init-container.sh

This is for HHVM on-demand servers when loading a build snapshot.

Add the configuration for VS Code extension recommendations

---

bin/test-build-on-all-distros

`git checkout-index` would be faster than `cp` when the work tree is not clean

Use `git checkout-index` instead of `cp` to prepare the source tarball 

---

bin/test-build-on-all-distros

#285 does not include submodules and the uploaded tarball would not build successfully on AWS. This PR fixes the problem

Include submodules to the tarball to upload

---

bin/test-build-on-all-distros

`/usr/bin/grep` on macOS does not support PCRE.
This PR also try to detect the version number from the current branch of the HHVM work tree, and fallback to the latest version only if the current branch is not a release branch.

Use bash pattern mathing instead of grep for macOS compatibility

---

bin/promote-nightly-to-release

Recently I removed `user.email` setting from my `~/.gitconfig`. As a result, when I ran `bin/promote-nightly-to-release`, it partially failed because it cannot commit to the `hhvm/hhvm-docker` repository. What is worse is that I could not rerun the script even when I added `user.email` back to `~/.gitconfig`, because it had created and pushed `HHVM-4.155` branch to this repository.
This PR lets the changes to this repository be idempotent, allowing me to rerun `promote-nightly-to-release` after a partial failure.

Make promote-nightly-to-release idempotent

---

bin/promote-nightly-to-release

Some users tend to not set `user.email` in `~/.gitconfig` to distinguish commits to personal repositories and company repositories. This PR allows for that practice.

When creating git commits, use the user.email and user.name from ./.git/config instead of ~/.gitconfig

---

RELEASE_PROCESS.md

These give a lot more context that is generally useful, but especially
for understanding the intent and changes required when making a
non-standard release.

Merge internal 'making a patched HHVM 4.x.0 release' docs

---

bin/make-source-tarball

Reverts hhvm/packaging#297
We stopped getting successful nightly builds due to failures in the MakeSourceTarball step the night after this landed. Trying to revert this to see if this is the cause.

Revert "Make a shallow clone in make-source-tarball"

---

aws/hhvm1/lambdas/deploy.sh

Without the argument, the deploy script will be paused several times

Add --no-cli-pager argument

---

aws/hhvm1/lambdas/activities.py

This PR avoids using Docker API v1, which has been deprecated and removed

Let PublishDockerImages.should_run return True

---

ubuntu-18.04-bionic/debian/rules

Recently the build pipeline on AWS is flaky. The error logs seem to be related with concurrent executions of `invoke_cargo.sh` when building the `hhbc_ast_cbindgen` target.
This PR tries to mitigate the flakiness by not building `hhbc_ast_cbindgen` in parallel.

Don't build hhbc_ast_cbindgen in parallel

---

ubuntu-18.04-bionic/debian/rules

Similar to #321, `hack_dune` would trigger `invoke_cargo.sh`, and some flaky builds happen when building `hack_dune`. This PR tries to mitigate the flakiness by not building `hack_dune` in parallel.

Don't build hack_dune in parallel
